# Generated by Django 2.2 on 2020-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_info', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_images')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='category_images')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('phone1', models.BigIntegerField()),
                ('phone2', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('form', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_us', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='home_images')),
                ('header_text_1', models.CharField(blank=True, max_length=500, null=True)),
                ('header_text_2', models.CharField(blank=True, max_length=500, null=True)),
                ('header_text_3', models.CharField(blank=True, max_length=500, null=True)),
                ('site_color', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home_images')),
                ('active', models.BooleanField(default=False)),
                ('website_name', models.CharField(blank=True, max_length=500, null=True)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('button', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('button_url', models.TextField(blank=True, null=True)),
                ('bgimage', models.ImageField(blank=True, null=True, upload_to='static_components')),
            ],
        ),
    ]
