# Generated by Django 2.2 on 2020-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
    ]
