# Generated by Django 2.2 on 2020-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0002_contactmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodule',
            name='value',
            field=models.TextField(default='{}'),
        ),
    ]
