# Generated by Django 2.2 on 2020-04-12 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0003_auto_20200412_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodule',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
