# Generated by Django 2.2 on 2020-04-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0004_auto_20200412_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercms',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footercms',
            name='google',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footercms',
            name='pinterest',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footercms',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='footercms',
            name='youtube',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
