# Generated by Django 3.0.2 on 2020-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0014_auto_20191231_1135'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='HomeComponents',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('key', models.CharField(max_length=50)),
        #         ('value', models.TextField()),
        #     ],
        # ),
    ]
