# Generated by Django 2.2 on 2020-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0016_auto_20200327_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecms',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='home_images'),
        ),
        migrations.AddField(
            model_name='homecms',
            name='site_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
