# Generated by Django 2.2 on 2020-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0017_auto_20200327_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcomponents',
            name='bgcolor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='button',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='name',
            field=models.CharField(help_text='Identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='title',
            field=models.CharField(help_text='Section Title', max_length=255),
        ),
    ]
