# Generated by Django 2.2 on 2020-03-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0019_staticcomponents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticcomponents',
            old_name='header',
            new_name='title',
        ),
    ]
