# Generated by Django 2.2 on 2020-03-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0019_auto_20200328_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcomponents',
            name='bgcolor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='button',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='button_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
