# Generated by Django 2.2 on 2020-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0020_auto_20200304_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticcomponents',
            old_name='title',
            new_name='name',
        ),
    ]
