# Generated by Django 2.2 on 2020-03-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0021_auto_20200306_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcomponents',
            name='button_url',
            field=models.URLField(default='#', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticcomponents',
            name='identifier',
            field=models.CharField(default='ss', max_length=50),
            preserve_default=False,
        ),
    ]
