# Generated by Django 2.2 on 2020-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0022_auto_20200306_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticcomponents',
            name='identifier',
        ),
        migrations.AddField(
            model_name='staticcomponents',
            name='title',
            field=models.CharField(default='ss', help_text='Section Title', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staticcomponents',
            name='name',
            field=models.CharField(help_text='Identifier', max_length=50),
        ),
    ]
