# Generated by Django 2.2 on 2020-04-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customCMS', '0020_auto_20200329_0000'),
        ('customCMS', '0023_auto_20200306_1136'),
    ]

    operations = [
    ]
