# Generated by Django 3.0.2 on 2020-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_updates_deleted_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='startup_images'),
        ),
    ]
