# Generated by Django 3.0.2 on 2020-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_startup_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
