# Generated by Django 3.0.2 on 2020-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_startup_thumbnail'),
    ]

    operations = [

    ]
