# Generated by Django 3.0.2 on 2020-01-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_startup_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='startup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_products', to='baseApp.StartUp'),
        ),
    ]
