# Generated by Django 3.0.2 on 2020-02-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_productratingsandreviews_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userImage', models.ImageField(upload_to='testimonial_images/')),
                ('testimonial', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Product')),
            ],
        ),
    ]
