# Generated by Django 2.2 on 2020-02-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_auto_20200211_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='pitch',
            field=models.TextField(default='{}'),
        ),
    ]
