<<<<<<< Updated upstream
# Generated by Django 2.2 on 2020-02-25 18:37
=======
# Generated by Django 3.0.2 on 2020-02-28 09:43
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
        ('baseApp', '0010_auto_20200211_1134'),
=======
        ('baseApp', '0010_producttestimonials'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='pitch',
<<<<<<< Updated upstream
            field=models.TextField(default='{}'),
=======
            field=models.TextField(default=''),
>>>>>>> Stashed changes
        ),
    ]
