# Generated by Django 3.0.2 on 2020-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_producttestimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='pitch',
            field=models.TextField(default=''),
        ),
    ]
