# Generated by Django 2.2 on 2020-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_startup_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='pitch',
            field=models.TextField(default=''),
        ),
    ]
