# Generated by Django 2.2 on 2020-03-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_startup_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_app_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
