# Generated by Django 2.2 on 2020-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_auto_20200329_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='pitch_file',
            field=models.FileField(blank=True, null=True, upload_to='pitch_images'),
        ),
    ]
