# Generated by Django 2.2 on 2020-04-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_auto_20200403_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
