# Generated by Django 2.2 on 2020-04-03 07:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_auto_20200403_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='added_date_timeline',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updates',
            name='added_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
