# Generated by Django 2.2 on 2020-04-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_auto_20200403_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='added_date_timeline',
        ),
    ]
