# Generated by Django 2.2 on 2020-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0018_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isVideo',
            field=models.BooleanField(default=False),
        ),
    ]
