# Generated by Django 2.2 on 2020-04-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_auto_20200303_2332'),
        ('baseApp', '0010_auto_20200211_1134'),
        ('baseApp', '0019_product_isvideo'),
    ]

    operations = [
    ]
